using System;
using System.Data.Entity;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    public partial class OnlineFiles_CatalogEntities : DbContext
    {
        public OnlineFiles_CatalogEntities(String connectionString)
            : base(connectionString)
        {
            Configuration.LazyLoadingEnabled = false;
        }
    }
}