//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogCollection
    {
        public CatalogCollection()
        {
            this.Catalogs = new HashSet<Catalog>();
            this.Folders = new HashSet<Folder>();
        }
    
        public System.Guid pk_CatalogCollectionId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Catalog> Catalogs { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
    }
}
