//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public Catalog()
        {
            this.FileDatas = new HashSet<FileData>();
        }
    
        public System.Guid pk_CatalogId { get; set; }
        public string Name { get; set; }
        public bool Offline { get; set; }
        public string Server { get; set; }
        public string DatabaseName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public WebDAVSharp.Data.Enums.CatalogStatus fk_CatalogStatusId { get; set; }
        public System.Guid fk_CatalogCollectionId { get; set; }
    
        public virtual CatalogStatu CatalogStatu { get; set; }
        public virtual ICollection<FileData> FileDatas { get; set; }
        public virtual CatalogCollection CatalogCollection { get; set; }
    }
}
