//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        internal File()
        {
            this.FileDatas = new HashSet<FileData>();
            this.FileSecurities = new HashSet<FileSecurity>();
        }
    
        public System.Guid pk_FileId { get; set; }
        public System.Guid fk_FolderId { get; internal set; }
        public string Name { get; set; }
        public bool isRevisioned { get; set; }
        public System.DateTime CreateDt { get; set; }
        public bool IsDeleted { get; internal set; }
        public string MimeType { get; internal set; }
        public int Win32FileAttribute { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; internal set; }
        public Nullable<System.Guid> DeletedById { get; internal set; }
        public System.Guid CreatedById { get; internal set; }
    
        public virtual Folder Folder { get; set; }
        public virtual ICollection<FileData> FileDatas { get; set; }
        public virtual SecurityObject Owner { get; set; }
        public virtual SecurityObject DeletedBy { get; set; }
        public virtual ICollection<FileSecurity> FileSecurities { get; set; }
        public virtual SecurityObject CreatedBy { get; set; }
    }
}
