//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public System.Guid pk_FileDataId { get; set; }
        public System.Guid fk_FileId { get; set; }
        public int Revision { get; set; }
        public int Size { get; set; }
        public System.DateTime CreateDt { get; set; }
        public System.Guid fk_CatalogId { get; set; }
        public System.Guid fk_ContentId { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual File File { get; set; }
    }
}
