//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileCatalogEntry
    {
        public System.Guid pk_FileCatalogEntryId { get; set; }
        public byte[] binaryData { get; set; }
    }
}
