//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSecurity
    {
        public System.Guid pk_FileSecurityId { get; internal set; }
        public System.Guid fk_FileId { get; internal set; }
        public System.Guid SecurityObjectId { get; internal set; }
        public bool canRead { get; internal set; }
        public bool canWrite { get; internal set; }
        public bool CanDelete { get; internal set; }
    
        public virtual File File { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
