//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        internal Folder()
        {
            this.Files = new HashSet<File>();
            this.ChildFolders = new HashSet<Folder>();
            this.HomeFolderTo = new HashSet<SecurityObject>();
            this.FolderSecurities = new HashSet<FolderSecurity>();
        }
    
        public System.Guid pk_FolderId { get; set; }
        public Nullable<System.Guid> fk_ParentFolderId { get; internal set; }
        public string Name { get; set; }
        public System.DateTime CreateDt { get; internal set; }
        public System.Guid fk_CatalogCollectionId { get; set; }
        public int Win32FileAttribute { get; set; }
        public bool IsDeleted { get; internal set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; internal set; }
        public Nullable<System.Guid> DeletedById { get; internal set; }
        public System.Guid CreatedById { get; internal set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Folder> ChildFolders { get; set; }
        public virtual Folder ParentFolder { get; set; }
        public virtual CatalogCollection CatalogCollection { get; set; }
        public virtual SecurityObject Owner { get; set; }
        public virtual SecurityObject DeletedBy { get; set; }
        public virtual ICollection<SecurityObject> HomeFolderTo { get; set; }
        public virtual ICollection<FolderSecurity> FolderSecurities { get; set; }
        public virtual SecurityObject CreatedBy { get; set; }
    }
}
