//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderSecurity
    {
        public System.Guid pk_FolderSecurityId { get; set; }
        public System.Guid fk_FolderId { get; set; }
        public System.Guid SecurityObjectId { get; set; }
        public bool canListObjects { get; internal set; }
        public bool canCreateFiles { get; internal set; }
        public bool canCreateFolders { get; internal set; }
        public bool canDelete { get; internal set; }
        public bool canChangePermissions { get; internal set; }
    
        public virtual Folder Folder { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
