//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectLockInfo
    {
        public System.Guid ObjectGuid { get; set; }
        public System.Guid Token { get; set; }
        public bool isFolder { get; set; }
        public int LockScope { get; set; }
        public int LockType { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<double> RequestedLockTimeout { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int Depth { get; set; }
        public string Path { get; set; }
        public System.DateTime CreateDt { get; set; }
    
        public virtual SecurityObject Owner { get; set; }
    }
}
