//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineFilesEntities : DbContext
    {
        public OnlineFilesEntities()
            : base("name=OnlineFilesEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            SecurityObjectMemberships = Set<SecurityObjectMembership>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalog> Catalogs { get; set; }
        public virtual DbSet<CatalogStatu> CatalogStatus { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileData> FileDatas { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<SecurityObject> SecurityObjects { get; set; }
        public virtual DbSet<SecurityObjectPermission> SecurityObjectPermissions { get; set; }
        public virtual DbSet<CatalogCollection> CatalogCollections { get; set; }
        public virtual DbSet<ObjectLockInfo> ObjectLockInfoes { get; set; }
        public virtual DbSet<FileSecurity> FileSecurities { get; set; }
        public virtual DbSet<FolderSecurity> FolderSecurities { get; set; }
        internal virtual DbSet<SecurityObjectMembership> SecurityObjectMemberships { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<SecurityObject> GetUserValidation(string username, string lDAP)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var lDAPParameter = lDAP != null ?
                new ObjectParameter("LDAP", lDAP) :
                new ObjectParameter("LDAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SecurityObject>("GetUserValidation", usernameParameter, lDAPParameter);
        }
    
        public virtual ObjectResult<SecurityObject> GetUserValidation(string username, string lDAP, MergeOption mergeOption)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var lDAPParameter = lDAP != null ?
                new ObjectParameter("LDAP", lDAP) :
                new ObjectParameter("LDAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SecurityObject>("GetUserValidation", mergeOption, usernameParameter, lDAPParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> GetSecurityTokens(Nullable<System.Guid> securityObjectId)
        {
            var securityObjectIdParameter = securityObjectId.HasValue ?
                new ObjectParameter("SecurityObjectId", securityObjectId) :
                new ObjectParameter("SecurityObjectId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("GetSecurityTokens", securityObjectIdParameter);
        }
    }
}
