//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    internal partial class SecurityObjectMembership
    {
        public System.Guid Id { get; set; }
        public System.Guid SecurityObjectId { get; set; }
        public System.Guid GroupSecurityObjectId { get; set; }
    
        public virtual SecurityObject OwnerSecurityObject { get; set; }
        public virtual SecurityObject GroupSecurityObject { get; set; }
    }
}
