//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAVSharp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityObjectPermission
    {
        public System.Guid SecurityObjectPermission1 { get; set; }
        public int PermissionId { get; set; }
        public System.Guid SecurityObjectId { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
